#!/usr/bin/env node
// Copies the extension's pure modules into the package, because npm cannot
// include files from outside a package directory and this one is published on
// its own. `npm test` fails if the copy has drifted, so the duplicate cannot
// quietly become a fork.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
export const SHARED = [{ from: join(here, '../../src/lib/chunk.js'), to: join(here, '../src/chunk.js') }];

export const HEADER = '// Generated by scripts/sync-lib.mjs from ../../src/lib/chunk.js.\n'
  + '// Do not edit here: edit the extension\'s copy and run `npm run sync:lib`.\n\n';

export const rendered = (source) => HEADER + readFileSync(source, 'utf8');

if (import.meta.url === `file://${process.argv[1]}`) {
  for (const { from, to } of SHARED) {
    writeFileSync(to, rendered(from));
    console.log(`synced ${to.split('/').slice(-2).join('/')}`);
  }
}
