// Starting with the computer, so nobody has to remember to.
//
// `start` detaches, which survives closing the terminal and not a reboot. A
// store you have to remember to turn on is a store that is missing the week you
// forgot, and the extension's captures queue up against nothing.
//
// Each platform's own mechanism rather than a supervisor of our own: systemd
// for Linux, launchd for macOS, the Startup folder for Windows. The file each
// one wants is generated by a pure function, so what gets written can be
// tested, printed, and read by the person before they agree to it.

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

export const LABEL = 'magpie-local';
export const BUNDLE_ID = 'com.anonalabs.magpie-local';

/**
 * How to run this copy, as a service manager must be told it.
 *
 * Never the `magpie-local` shim: that is a file beginning `#!/usr/bin/env
 * node`, and `env` searches a PATH that belongs to whoever started the
 * process. systemd's PATH is not a login shell's, and on a machine with nvm it
 * found the system Node 18, which has no `node:sqlite` at all. The service
 * started, failed on an unknown builtin module, and retried forever.
 *
 * So: this exact node binary, and the script the shim points at, both absolute.
 * The cost is that moving or removing this Node installation breaks the unit,
 * which is a thing you can read in the file rather than a mystery.
 */
export function selfExec({
  argv = process.argv,
  execPath = process.execPath,
  realpath = realpathSync,
} = {}) {
  const script = argv[1] ?? '';
  try {
    return { exec: execPath, args: [realpath(script), 'serve'] };
  } catch {
    // A path that cannot be resolved is still better named than guessed at.
    return { exec: execPath, args: [script, 'serve'] };
  }
}

/**
 * What to write, where, and what to run afterwards.
 *
 * `exec` is how this copy of magpie-local is run: the node binary and the path
 * to the CLI, or the installed `magpie-local` shim. It is resolved by the
 * caller from the running process, so a checkout and a global install both
 * produce a service that points at themselves rather than at a guess.
 */
export function serviceFile({ platform, exec, args = ['serve'], home = homedir(), port, logPath }) {
  const command = [exec, ...args];

  if (platform === 'linux') {
    return {
      path: join(home, '.config/systemd/user', `${LABEL}.service`),
      contents: [
        '[Unit]',
        'Description=magpie-local: a memory store on this machine',
        'Documentation=https://github.com/anonalabs/magpie/tree/main/local',
        'After=network.target',
        '',
        '[Service]',
        'Type=simple',
        `ExecStart=${command.map(quote).join(' ')}`,
        port ? `Environment=MAGPIE_PORT=${port}` : null,
        'Restart=on-failure',
        'RestartSec=5',
        '',
        '[Install]',
        'WantedBy=default.target',
        '',
      ].filter((line) => line !== null).join('\n'),
      enable: [
        ['systemctl', ['--user', 'daemon-reload']],
        ['systemctl', ['--user', 'enable', '--now', LABEL]],
      ],
      disable: [
        ['systemctl', ['--user', 'disable', '--now', LABEL]],
        ['systemctl', ['--user', 'daemon-reload']],
      ],
      // Without lingering it starts when you log in, which is the right moment
      // for something the browser talks to, and stops when you log out.
      note: 'It starts when you log in. For it to run with nobody logged in: '
        + `loginctl enable-linger ${process.env.USER ?? '$USER'}`,
    };
  }

  if (platform === 'darwin') {
    const plist = join(home, 'Library/LaunchAgents', `${BUNDLE_ID}.plist`);
    return {
      path: plist,
      contents: [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<plist version="1.0">',
        '<dict>',
        '  <key>Label</key>',
        `  <string>${BUNDLE_ID}</string>`,
        '  <key>ProgramArguments</key>',
        '  <array>',
        ...command.map((part) => `    <string>${escapeXml(part)}</string>`),
        '  </array>',
        '  <key>RunAtLoad</key>',
        '  <true/>',
        '  <key>KeepAlive</key>',
        '  <dict><key>SuccessfulExit</key><false/></dict>',
        ...(port ? [
          '  <key>EnvironmentVariables</key>',
          `  <dict><key>MAGPIE_PORT</key><string>${port}</string></dict>`,
        ] : []),
        ...(logPath ? [
          '  <key>StandardOutPath</key>',
          `  <string>${escapeXml(logPath)}</string>`,
          '  <key>StandardErrorPath</key>',
          `  <string>${escapeXml(logPath)}</string>`,
        ] : []),
        '</dict>',
        '</plist>',
        '',
      ].join('\n'),
      enable: [['launchctl', ['load', '-w', plist]]],
      disable: [['launchctl', ['unload', '-w', plist]]],
      note: 'It starts when you log in.',
    };
  }

  if (platform === 'win32') {
    return {
      path: join(home, 'AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup', `${LABEL}.cmd`),
      // `start ""` so the window closes and the process keeps going, which is
      // the Windows equivalent of detaching.
      contents: `@echo off\r\n${port ? `set MAGPIE_PORT=${port}\r\n` : ''}`
        + `start "" /b ${command.map((part) => `"${part}"`).join(' ')}\r\n`,
      enable: [],
      disable: [],
      note: 'It starts when you log in. Nothing else to run: the file being there is the install.',
    };
  }

  return null;
}

const quote = (part) => (/\s/.test(part) ? `"${part}"` : part);
const escapeXml = (text) => String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Whether a service file has been written for this platform. */
export function installed(platform = process.platform, home = homedir()) {
  const plan = serviceFile({ platform, exec: 'node', home });
  return Boolean(plan && existsSync(plan.path));
}

export function install(plan, { run = true } = {}) {
  mkdirSync(dirname(plan.path), { recursive: true });
  writeFileSync(plan.path, plan.contents);

  const ran = [];
  if (run) {
    for (const [cmd, args] of plan.enable) {
      try {
        execFileSync(cmd, args, { stdio: 'pipe' });
        ran.push(`${cmd} ${args.join(' ')}`);
      } catch (err) {
        // The file is written either way; a missing systemctl or a session
        // without a user bus is a thing to report, not a reason to leave half
        // an install behind.
        return { path: plan.path, ran, failed: `${cmd} ${args.join(' ')}`, error: String(err.message ?? err).split('\n')[0] };
      }
    }
  }
  return { path: plan.path, ran };
}

export function uninstall(plan) {
  const ran = [];
  for (const [cmd, args] of plan.disable) {
    try { execFileSync(cmd, args, { stdio: 'pipe' }); ran.push(`${cmd} ${args.join(' ')}`); } catch { /* it may never have been enabled */ }
  }
  const existed = existsSync(plan.path);
  rmSync(plan.path, { force: true });
  return { path: plan.path, existed, ran };
}
